import { StyleProp, TextStyle } from 'react-native'

export const scrollbar: StyleProp<TextStyle>
export const overlay: StyleProp<TextStyle>
export const tooltip-inner: StyleProp<TextStyle>
export const modal-open: StyleProp<TextStyle>
export const linkBox: StyleProp<TextStyle>
export const servicesType: StyleProp<TextStyle>
export const box: StyleProp<TextStyle>
export const see-more: StyleProp<TextStyle>
export const wrapper: StyleProp<TextStyle>
export const image: StyleProp<TextStyle>
export const btn: StyleProp<TextStyle>
export const main-title: StyleProp<TextStyle>
export const viewMore: StyleProp<TextStyle>
export const pageHead: StyleProp<TextStyle>
export const remove-cart: StyleProp<TextStyle>
export const tableResponsive: StyleProp<TextStyle>
export const show-on-lg: StyleProp<TextStyle>
export const tableDesktop: StyleProp<TextStyle>
export const table: StyleProp<TextStyle>
export const uploadFiles: StyleProp<TextStyle>
export const contentBox: StyleProp<TextStyle>
export const d-none-767: StyleProp<TextStyle>
export const d-show-767: StyleProp<TextStyle>
export const pagination: StyleProp<TextStyle>
export const page-item: StyleProp<TextStyle>
export const page-link: StyleProp<TextStyle>
export const active: StyleProp<TextStyle>
export const bestSeller: StyleProp<TextStyle>
export const inner-title: StyleProp<TextStyle>
export const caseSteps: StyleProp<TextStyle>
export const counter: StyleProp<TextStyle>
export const not-collapsed: StyleProp<TextStyle>
export const rowcol-reverse-lg: StyleProp<TextStyle>
export const card: StyleProp<TextStyle>
export const has-border: StyleProp<TextStyle>
export const tab-content: StyleProp<TextStyle>
export const card__body: StyleProp<TextStyle>
export const card__head: StyleProp<TextStyle>
export const textWrapper: StyleProp<TextStyle>
export const inline-btns-wrapper: StyleProp<TextStyle>
export const completed: StyleProp<TextStyle>
export const current: StyleProp<TextStyle>
export const pending: StyleProp<TextStyle>
export const serviceRow: StyleProp<TextStyle>
export const d-flex: StyleProp<TextStyle>
export const stack-on-sm: StyleProp<TextStyle>
