import { StyleProp, TextStyle } from 'react-native'

export const mb-#$item}: StyleProp<TextStyle>
export const mt-#$item}: StyleProp<TextStyle>
export const pb-#$item}: StyleProp<TextStyle>
export const pt-#$item}: StyleProp<TextStyle>
export const col-gap-#$item}: StyleProp<TextStyle>
export const col-gap-#$item}>div: StyleProp<TextStyle>
export const grid: StyleProp<TextStyle>
export const card: StyleProp<TextStyle>
export const dropzone: StyleProp<TextStyle>
export const dz-message: StyleProp<TextStyle>
export const dz-button: StyleProp<TextStyle>
export const note: StyleProp<TextStyle>
export const dz-preview: StyleProp<TextStyle>
export const dz-image: StyleProp<TextStyle>
export const mb-35: StyleProp<TextStyle>
export const mt-15: StyleProp<TextStyle>
export const accordion: StyleProp<TextStyle>
export const card-header: StyleProp<TextStyle>
export const btn: StyleProp<TextStyle>
export const badge-light: StyleProp<TextStyle>
export const not-collapsed: StyleProp<TextStyle>
export const card-body: StyleProp<TextStyle>
export const steps: StyleProp<TextStyle>
export const patientType: StyleProp<TextStyle>
export const contentBox: StyleProp<TextStyle>
export const wrapper: StyleProp<TextStyle>
export const card__body: StyleProp<TextStyle>
export const patientType__wrapper: StyleProp<TextStyle>
export const image: StyleProp<TextStyle>
export const active::before: StyleProp<TextStyle>
export const navnav-tabs: StyleProp<TextStyle>
export const nav-link: StyleProp<TextStyle>
export const active: StyleProp<TextStyle>
export const navnav-pills: StyleProp<TextStyle>
export const abs-link: StyleProp<TextStyle>
export const table: StyleProp<TextStyle>
export const phase: StyleProp<TextStyle>
export const result: StyleProp<TextStyle>
export const blue: StyleProp<TextStyle>
export const text-turncate: StyleProp<TextStyle>
export const pending: StyleProp<TextStyle>
export const completed: StyleProp<TextStyle>
export const failed: StyleProp<TextStyle>
export const cancelled: StyleProp<TextStyle>
export const refunded: StyleProp<TextStyle>
export const table__row--cell: StyleProp<TextStyle>
export const dropdownaction-dropdown: StyleProp<TextStyle>
export const btn:focus: StyleProp<TextStyle>
export const dropdown-toggle: StyleProp<TextStyle>
export const dropdown-menu: StyleProp<TextStyle>
export const dropdownTitle: StyleProp<TextStyle>
export const dropdown: StyleProp<TextStyle>
export const b-dropdown-item: StyleProp<TextStyle>
export const show: StyleProp<TextStyle>
export const b-0: StyleProp<TextStyle>
export const nav__tabs: StyleProp<TextStyle>
export const img-lazyloader: StyleProp<TextStyle>
export const image-hover: StyleProp<TextStyle>
export const detail-list: StyleProp<TextStyle>
export const two-columns: StyleProp<TextStyle>
export const icon: StyleProp<TextStyle>
export const area: StyleProp<TextStyle>
export const front-page: StyleProp<TextStyle>
export const progress-container: StyleProp<TextStyle>
export const progress: StyleProp<TextStyle>
export const progress-bar: StyleProp<TextStyle>
export const checkbox--switch: StyleProp<TextStyle>
export const custom__tooltip: StyleProp<TextStyle>
export const custom__tooltip--content: StyleProp<TextStyle>
export const mCSB_scrollTools: StyleProp<TextStyle>
export const mCSB_dragger: StyleProp<TextStyle>
export const mCSB_dragger_bar: StyleProp<TextStyle>
export const mCSB_draggerRail: StyleProp<TextStyle>
export const mCSB_draggerContainer: StyleProp<TextStyle>
export const loadmore: StyleProp<TextStyle>
export const contentWrapper: StyleProp<TextStyle>
export const container: StyleProp<TextStyle>
