import { StyleProp, TextStyle } from 'react-native'

export const button-row: StyleProp<TextStyle>
export const list-inline-item:not(:last-child): StyleProp<TextStyle>
export const inline-btns-wrapper: StyleProp<TextStyle>
export const btn: StyleProp<TextStyle>
export const inline-btns: StyleProp<TextStyle>
export const btnbtn-primary: StyleProp<TextStyle>
export const btnbtn-secondary: StyleProp<TextStyle>
export const ar: StyleProp<TextStyle>
export const btn-secondary: StyleProp<TextStyle>
export const dropdown-toggle: StyleProp<TextStyle>
export const btn-small: StyleProp<TextStyle>
export const icon: StyleProp<TextStyle>
export const big: StyleProp<TextStyle>
export const only-icon: StyleProp<TextStyle>
export const full: StyleProp<TextStyle>
export const btn-primary:active: StyleProp<TextStyle>
export const green: StyleProp<TextStyle>
export const orange: StyleProp<TextStyle>
export const grey: StyleProp<TextStyle>
export const pink: StyleProp<TextStyle>
export const btn-default: StyleProp<TextStyle>
export const show-loading: StyleProp<TextStyle>
export const btn-upload: StyleProp<TextStyle>
export const radio: StyleProp<TextStyle>
export const dropdownbootstrap-select: StyleProp<TextStyle>
export const btn-lightdropdown-toggle:focus: StyleProp<TextStyle>
export const mobile-device: StyleProp<TextStyle>
export const dropdown-toggle:focus: StyleProp<TextStyle>
export const b-form-datepicker: StyleProp<TextStyle>
export const form-controltext-muted: StyleProp<TextStyle>
export const active: StyleProp<TextStyle>
export const b-form-btn-label-control: StyleProp<TextStyle>
export const h-auto: StyleProp<TextStyle>
export const dropdown-menu: StyleProp<TextStyle>
export const form-control: StyleProp<TextStyle>
export const btnactive: StyleProp<TextStyle>
export const b-calendar-grid-weekdays: StyleProp<TextStyle>
export const b-calendar-header: StyleProp<TextStyle>
export const b-calendar-nav: StyleProp<TextStyle>
